import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Chat from "@/components/Chat";
import { Navbar } from "@/components/Navbar";
import { Rail } from "@/components/Rail";
import { Sidebar } from "@/components/Sidebar";
import { Statusbar } from "@/components/Statusbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <div className="h-[100dvh] flex flex-col">
      <Navbar />
      <div className="grow flex">
        <Rail />
        <Sidebar />
        <main className="grow p-4">{children}</main>
        <Chat />
      </div>
      <Statusbar />
    </div>  
        </ThemeProvider>
      </body>
    </html>
  );
}
